apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-volume
  namespace: rupesh
  labels:
    apps: my-configmap-volume
spec:
  containers:
  - name: my-configmap-vol-container
    image: busybox
    command: [ 'sh', '-c', 'ls /etc/config && sleep 3600' ]
    volumeMounts:
      - name: config-volume 
        mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: properties
