apiVersion: v1
kind: Pod
metadata:
  name: config-map-env
  namespace: rupesh
  labels:
    apps: config-map
spec:
  containers:
  - name: config-map-env-container
    image: busybox
    command: [ 'sh', '-c', "echo Application Name : $(application_name) running on $(host_name)&& sleep 3600"]
    env:
    - name: application_name
      valueFrom:
        configMapKeyRef:
         name: properties
         key: name

    - name: host_name
      valueFrom:
        configMapKeyRef:
         name: properties
         key: hostname
