apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-secrets
  namespace: rupesh
  labels:
    apps: app-with-secret
spec:
  containers:
  - name: container-with-secret
    image: busybox
    command: ['sh', '-c', 'echo $mypassword && sleep 3600' ]
    env:
    - name: mypassword
      valueFrom: 
        secretKeyRef:
          name: myscrets
          key: password
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/secrets"
  volumes:
  - name: secret-vol
    secret:
      secretName: myscrets
